### ISSUE TITLE
Mac fails on `cmake --build .`

### ISSUE THREAD

**Issue by Gcat101** [Kuplynx/ccwfetch#1]
Log is attached:

[ccwfetchmac.log](https://github.com/Kuplynx/ccwfetch/files/7783677/ccwfetchmac.log)

**Comment by Kuplynx** [comment]
This appears to be an issue with the C++ standard that is being used by the cmake. Are you able to set it to C++ 17 which is what this is made for? It seems you are using a version of C++ before 11

**Comment by Kuplynx** [comment]
I've also updated it so it should be building in the right config if you follow the readme steps.

**Comment by Gcat101** [comment]
`'include/curl/curl.h' file not found`

And when I change it to 'curl/curl.h' it gives:

[ccweftchmac.log](https://github.com/Kuplynx/ccwfetch/files/7786138/ccweftchmac.log)

**Comment by Gcat101** [comment]
I added 
```
set(CMAKE_CXX_STANDARD 17) 
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
to CMakeLists.txt, btw

**Comment by Kuplynx** [comment]
Did it work?

**Comment by Kuplynx** [comment]
> `'include/curl/curl.h' file not found`
Yeah I'm currently fixing that. It was because I moved header files. I'm almost done with adding the CLI interface and it'll fix that.

**Comment by Gcat101** [comment]
> `'include/curl/curl.h' file not found`
> 
> 
> 
> And when I change it to 'curl/curl.h' it gives:
> 
> 
> 
> [ccweftchmac.log](https://github.com/Kuplynx/ccwfetch/files/7786138/ccweftchmac.log)
> 
> 

No, it didn't

**Comment by Kuplynx** [comment]
You're still somehow compiling in a very old C++ version. The only errors are about a part of C++ 11.

**Comment by Gcat101** [comment]
Ok I figured out a way to change the standard, now it throws:

[Uploading maclogfile3.log…]()

**Comment by Kuplynx** [comment]
Are you on a M1 Mac? It complaining about "ld: symbol(s) not found for architecture x86_64" and "Undefined symbols for architecture x86_64"  make it seem like you're on a different architecture.  "clang: error: linker command failed with exit code 1 (use -v to see invocation)" try using the -v tag?

**Comment by Gcat101** [comment]
I am using the -v flag.
I'm on intel.

**Comment by Kuplynx** [comment]
I would try adding a _ to all curl functions. It complained about something like that.

**Comment by Gcat101** [comment]
I (finally) managed to get it working! I compiled it through g++ like that:
`g++ -o ccwfetch ccwfetch.cpp -lcurl -std=c++17`
Closing this!

**Comment by Gcat101** [comment]
[Oh and here's an executable](https://drive.google.com/file/d/1Kl-3tfE4g-X5Pu293rrSwIoj7NDb2_t_/view?usp=sharing)

**Comment by Kuplynx** [comment]
Ok Great! When I update it today (almost done with colors!) just need to do ascii art. Do you have any tips on that?

**Comment by Gcat101** [comment]
No. I just did the first thing that came up in my head.

**Comment by Kuplynx** [comment]
Ok, do you mind if I use some of the ascii art that you have in your project?

**Comment by Gcat101** [comment]
Of course I wouldn't mind, It's under GPL 3.0
